development:
  access_key: AKIAI25NMQARPZDAQHYA
  secret_access_key: 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
  bucket_name: fosem-staging
  region: ap-southeast-1
  storage: :file

staging:
  access_key: AKIAI25NMQARPZDAQHYA
  secret_access_key: 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
  bucket_name: fosem-staging
  region: ap-southeast-1
  storage: :fog