# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecc9171f41950749499f01c1ebd4f1ebeb2d03e76d4e8896dc0a0ddb960bc090ab9241c5c2a7c3be189f056787f5a8130573d270e75235c780c0996da5f59b7e

test:
  secret_key_base: 3359be411d805f7854bf9146754dabc757bcb08e792e50f92d70c11fe0a8ad0581d4b259ae1e62257738c9dc9a8cfcdf037262b3c38af9ab4284512231f2ea18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
