class CreateShopAudits < ActiveRecord::Migration
  def change
    create_table :shop_audits do |t| 
    	t.integer :audit_type
        t.string  :avg_monthly_sale  
        t.string  :most_selling_brand
        t.string  :second_most_selling_brand 
        t.string  :third_most_selling_brand
        t.string  :gionee_sales
        t.string  :gionee_stock_quantity
        t.text    :models_available	
    	t.integer :no_of_flange
    	t.boolean :flange_delivered
    	t.boolean :flange_installation
    	t.string  :flange_condition
    	t.boolean :flange_avilable
    	t.integer :no_of_lit_standee
    	t.boolean :lit_standee_delivered
    	t.boolean :lit_standee_installation
    	t.string  :lit_standee_condition
    	t.boolean :lit_standee_available
    	t.integer :no_of_leaflet
    	t.boolean :leaflet_delivered
    	t.boolean :leaflet_installation
    	t.integer :no_of_brochure
    	t.boolean :brochure_delivered
    	t.boolean :brochure_installation
    	t.integer :no_of_dangler
    	t.boolean :dangler_delivered
    	t.boolean :dangler_installation
    	t.integer :no_of_shelf_strip
    	t.boolean :shelf_strip_delivered
    	t.boolean :shelf_strip_installation
    	t.integer :no_of_sticker
    	t.boolean :sticker_delivered
    	t.boolean :sticker_installation
    	t.integer :no_of_poster
    	t.boolean :poster_delivered
    	t.boolean :poster_installation
    	t.integer :no_of_demo
    	t.boolean :demo_delivered
    	t.boolean :demo_installation
    	t.string  :demo_condition
    	t.boolean :demo_available
    	t.integer :no_of_dummy
    	t.boolean :dummy_delivered
    	t.boolean :dummy_installation
    	t.string  :dummy_condition
    	t.boolean :dummy_available
    	t.integer :no_of_spec_card
    	t.boolean :spec_card_delivered
    	t.boolean :spec_card_installation
    	t.integer :no_of_cables
    	t.boolean :cables_delivered
    	t.boolean :cables_installation
    	t.integer :no_of_pods
    	t.boolean :pods_delivered
    	t.boolean :pods_installation
    	t.integer :no_of_security_system
    	t.boolean :security_system_delivered
    	t.boolean :security_system_installation
    	t.integer :no_of_countertop
    	t.boolean :countertop_delivered
    	t.boolean :countertop_installation
    	t.string  :countertop_condition
    	t.boolean :countertop_available 
    	t.integer :no_of_gift_item
    	t.boolean :gift_item_delivered
    	t.boolean :gift_item_installation
    	t.integer :no_of_tshirt
    	t.boolean :tshirt_delivered
    	t.boolean :tshirt_installation
    	t.integer :no_of_rollupstandee
    	t.boolean :rollupstandee_delivered
    	t.boolean :rollupstandee_installation
    	t.integer :no_of_clipon
    	t.boolean :clipon_delivered
    	t.boolean :clipon_installation
    	t.string  :clipon_condition
    	t.boolean :clipon_available
    	t.integer :no_of_cubes
    	t.boolean :cubes_delivered
    	t.boolean :cubes_installation
    	t.integer :no_of_balloons
    	t.boolean :balloons_delivered
    	t.boolean :balloons_installation
    	t.boolean :gsb_present 
    	t.boolean :sis_present 
    	t.boolean :lit_standee_present 
    	t.boolean :flange_present 
    	t.boolean :countertop_present 
    	t.boolean :clipon_present 
    	t.boolean :changed_visual_gsb 
    	t.boolean :changed_visual_sis 
    	t.boolean :changed_visual_lit_standee 
    	t.boolean :changed_visual_flange 
    	t.boolean :changed_visual_countertop
    	t.boolean :changed_visual_clipon
    	t.boolean :cleaned_and_checked_gsb 
    	t.boolean :cleaned_and_checked_sis 
    	t.boolean :cleaned_and_checked_lit_standee
    	t.boolean :cleaned_and_checked_flange
    	t.boolean :cleaned_and_checked_countertop
    	t.string  :maintenance_done_on
    	t.text    :consumnables_used
    	t.string  :type_of_issue
    	t.boolean :maintenance_done
    	t.boolean :problem_solved
    	t.boolean :checkbox_escalate
    	t.boolean :sis_present_in_store
    	t.string  :sis_type
    	t.integer :back_wall_nos
    	t.integer :glass_counter_no
    	t.integer :experience_counter_no
    	t.string  :sis_condition
    	t.string  :sis_needs
    	t.integer :no_of_gsb
    	t.string  :gsb_type_installed
    	t.string  :gsb_type_logo
    	t.string  :gsb_position
    	t.string  :gsb_condition
    	t.string  :gsb_size
    	t.boolean :gsb_present_at_store
    	t.text    :dummy_models
    	t.text    :clipon_models
    	t.text    :lit_standee_models
    	t.text    :countertop_models
    	t.text    :demo_models
     end
     add_reference :shop_audits,:request
  end
end
