require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RequestAssignmentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RequestAssignment. As you add validations to RequestAssignment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequestAssignmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all request_assignments as @request_assignments" do
      request_assignment = RequestAssignment.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:request_assignments)).to eq([request_assignment])
    end
  end

  describe "GET #show" do
    it "assigns the requested request_assignment as @request_assignment" do
      request_assignment = RequestAssignment.create! valid_attributes
      get :show, {:id => request_assignment.to_param}, valid_session
      expect(assigns(:request_assignment)).to eq(request_assignment)
    end
  end

  describe "GET #new" do
    it "assigns a new request_assignment as @request_assignment" do
      get :new, {}, valid_session
      expect(assigns(:request_assignment)).to be_a_new(RequestAssignment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested request_assignment as @request_assignment" do
      request_assignment = RequestAssignment.create! valid_attributes
      get :edit, {:id => request_assignment.to_param}, valid_session
      expect(assigns(:request_assignment)).to eq(request_assignment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RequestAssignment" do
        expect {
          post :create, {:request_assignment => valid_attributes}, valid_session
        }.to change(RequestAssignment, :count).by(1)
      end

      it "assigns a newly created request_assignment as @request_assignment" do
        post :create, {:request_assignment => valid_attributes}, valid_session
        expect(assigns(:request_assignment)).to be_a(RequestAssignment)
        expect(assigns(:request_assignment)).to be_persisted
      end

      it "redirects to the created request_assignment" do
        post :create, {:request_assignment => valid_attributes}, valid_session
        expect(response).to redirect_to(RequestAssignment.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved request_assignment as @request_assignment" do
        post :create, {:request_assignment => invalid_attributes}, valid_session
        expect(assigns(:request_assignment)).to be_a_new(RequestAssignment)
      end

      it "re-renders the 'new' template" do
        post :create, {:request_assignment => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested request_assignment" do
        request_assignment = RequestAssignment.create! valid_attributes
        put :update, {:id => request_assignment.to_param, :request_assignment => new_attributes}, valid_session
        request_assignment.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested request_assignment as @request_assignment" do
        request_assignment = RequestAssignment.create! valid_attributes
        put :update, {:id => request_assignment.to_param, :request_assignment => valid_attributes}, valid_session
        expect(assigns(:request_assignment)).to eq(request_assignment)
      end

      it "redirects to the request_assignment" do
        request_assignment = RequestAssignment.create! valid_attributes
        put :update, {:id => request_assignment.to_param, :request_assignment => valid_attributes}, valid_session
        expect(response).to redirect_to(request_assignment)
      end
    end

    context "with invalid params" do
      it "assigns the request_assignment as @request_assignment" do
        request_assignment = RequestAssignment.create! valid_attributes
        put :update, {:id => request_assignment.to_param, :request_assignment => invalid_attributes}, valid_session
        expect(assigns(:request_assignment)).to eq(request_assignment)
      end

      it "re-renders the 'edit' template" do
        request_assignment = RequestAssignment.create! valid_attributes
        put :update, {:id => request_assignment.to_param, :request_assignment => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested request_assignment" do
      request_assignment = RequestAssignment.create! valid_attributes
      expect {
        delete :destroy, {:id => request_assignment.to_param}, valid_session
      }.to change(RequestAssignment, :count).by(-1)
    end

    it "redirects to the request_assignments list" do
      request_assignment = RequestAssignment.create! valid_attributes
      delete :destroy, {:id => request_assignment.to_param}, valid_session
      expect(response).to redirect_to(request_assignments_url)
    end
  end

end
